### ISSUE TITLE
How to get data for multiple hosts/containers

### ISSUE THREAD

**Issue by CodingSpiderFox** [7insyde/env-tick-templates#2]
Hello,

I really like this stack!
It worked very good, even for me as I am a beginner with docker.

Could you please add a little HowTo on how I can add multiple docker hosts and their containers to the stack so I can see them in the Grafana instance?

I guess I need docker swarm to achieve this, right?

Best regards

**Comment by Y4Rv1K** [comment]
@CodingSpiderFox that little outdated version of TICK stack. We will upgrade stack i nearly future. 
Still, 

>Could you please add a little HowTo on how I can add multiple docker hosts and their containers to the stack so I can see them in the Grafana instance?

If you are planing  to use Swarm to manage this docker host in this case  yes. But you can use any other container management system aka Kubernetes, ECS, Rancher etc. 

I would recommend to take a look at [this article](http://dev.haufe.io/monitoring-docker-environment/) in case if you chose Rancher

**Comment by CodingSpiderFox** [comment]
Thanks for the link. Unfortunately I can't get it working.

I don't understand the $(curl "http://rancher-metadata/2015-07-25/self/host/hostname") line in the start_telegraf.sh . Where do I find the hostname "rancher-metadata" ? What service is expected to be written in the INFLUX_TELEGRAF_HOST variable.?

**Comment by Y4Rv1K** [comment]
You should put IP address or FQDN of your InfluxDB server. 

> I don't understand the $(curl "http://rancher-metadata/2015-07-25/self/host/hostname") line in the start_telegraf.sh . Where do I find the hostname "rancher-metadata" ? 

If you aren't using Rancher in this case you don't need it. 
This manual related to specific installation under Rancher cluster. 

You need only modify config file at your agent: 

     [agent] 
      ## Override default hostname, if empty use os.Hostname()
      hostname = "_put_here_IP_or_FQDN_of_InfluxDB_"

**Comment by CodingSpiderFox** [comment]
So on the remote agent, I only start the telegraf container then, right?

**Comment by CodingSpiderFox** [comment]
So I also have to modify the docker image of telegraf, too, right?

**Comment by CodingSpiderFox** [comment]
Not relevant to me anymore
